<a href="https://colab.research.google.com/github/trex99/DAVI/blob/main/%EA%B3%BC%EC%A0%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EA%B3%BC%EC%8B%9C%EA%B0%81%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과목명 : 데이터분석과 시각화

## 과제설명

1. 아래 내용을 읽고 각 문제를 해결하는 코드를 완성하여 PDF로 제출하시기 바랍니다.
2. PDF가 아닌 노트북 파일 또는 Colab을 공유하여 제출하는 경우 감점이 됩니다.
3. 코드 이외 설명하는 내용 등 코드와 관계없는  내용이 포함되어도 관계없습니다.

## 과제제출

- 15주차 기말고사 일자이전에 제출

<hr>

## 문제상황

### 데이타 사전 지식

YouTube(세계적으로 유명한 동영상 공유 웹사이트)는 플랫폼에서 가장 인기 있는 동영상 목록을 관리합니다. 

버라이어티 매거진에 따르면 올해의 최고 인기 동영상을 결정하기 위해 YouTube는 사용자 상호 작용(조회 수, 공유 수, 댓글 및 좋아요 수)을 측정하는 등 여러 요인을 조합하여 사용합니다. 해당 연도 전체에서 가장 많이 본 동영상은 아닙니다.

YouTube 트렌딩 목록의 최고 성능은 뮤직 비디오(유명하게 남성적인 "Gangam Style" 등), 유명인 및/또는 리얼리티 TV 공연, YouTube에서 잘 알려진 무작위 카메라 바이럴 동영상입니다.

분석대상 데이터 셋은 인기 급상승 YouTube 동영상의 일일 기록입니다.

### 분석대상 데이터셋

- 분석 대상 데이터셋 : https://www.kaggle.com/datasets/datasnaek/youtube-new?select=KRvideos.csv
- 학습 공유 구글 드라이브에도 있습니다
- 파일명 : KRvideos.csv

### 과제 목표

- 분석 대상 데이터셋을 불러와 기술 통계정보를 확인합니다.
- 결측치를 확인하고 0 으로 치환 처리합니다.
- 중복된 데이터가 있다면 데이터 건수를 확인하고 삭제합니다.
- 채널별 조회수 합계를 구하고 시각화합니다.
- 채널별 조회수 합계를 구하고 상위 100건에 대해 시각화합니다.
- 'title','views'만 선택하여 많은 views 순으로 정렬 후 중복을 제거합니다.
- 'title' 컬럼 값을 이용하여 한글만 워드 클라우드 시각화를 합니다.
- 'views', 'likes', 'dislikes', 'comment_count' 컬럼 값의 상관계수 heatmap() 시각화를 합니다.
- 'category_id', 'views', 'likes', 'comment_count' 컬럼을 이용하여 유의미한 scatterplot(), barplot(), histplot(), countplot() 등 시각화를 합니다.

In [ ]:
import pandas as pd

KRvideo = pd.read_csv("KRvideos.csv")
KRvideo

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,RxGQe4EeEpA,17.14.11,좋아 by 민서_윤종신_좋니 답가,라푸마코리아,22,2017-11-13T07:07:36.000Z,"라푸마|""윤종신""|""좋니""|""좋아""|""샬레""|""민서""",156130,1422,40,272,https://i.ytimg.com/vi/RxGQe4EeEpA/default.jpg,False,False,False,윤종신 '좋니'의 답가 '좋아' 최초 공개!\n그 여자의 이야기를 지금 만나보세요....
1,hH7wVE8OlQ0,17.14.11,JSA 귀순 북한군 총격 부상,Edward,25,2017-11-13T10:59:16.000Z,"JSA|""귀순""|""북한군""|""총격""|""부상""|""JSA 귀순 북한군 총격 부상""",76533,211,28,113,https://i.ytimg.com/vi/hH7wVE8OlQ0/default.jpg,False,False,False,[채널A단독]北 병사 현재 '의식불명'… 혈압 떨어지는 중 \n[채널A단독]우리측 ...
2,9V8bnWUmE9U,17.14.11,나몰라패밀리 운동화 영상 2탄 (빼빼로데이버젼),나몰라패밀리 핫쇼,22,2017-11-11T07:16:08.000Z,"아디다스|""빼빼로""|""핫쇼""|""나몰라패밀리""|""대학로""|""공연""",421409,5112,166,459,https://i.ytimg.com/vi/9V8bnWUmE9U/default.jpg,False,False,False,퍼가실때 꼭 출처 부탁드려요
3,0_8py-t5R80,17.14.11,"이명박 출국 현장, 놓치면 안되는 장면",미디어몽구,25,2017-11-12T11:19:52.000Z,"이명박|""이명박 출국금지""|""이명박 출국현장""|""이명박 바레인""|""이명박 대통령""|...",222850,2093,173,1219,https://i.ytimg.com/vi/0_8py-t5R80/default.jpg,False,False,False,다스는 누구겁니까 듣고 난 후 표정
4,bk55RbxiQdI,17.14.11,김장겸은 물러갔다 MBC 노조 환호와 눈물,NocutV,25,2017-11-13T11:08:59.000Z,"nocutV|""노컷V""|""CBS""|""mbc""|""김장겸""|""해임""|""허일후""",84466,1094,109,450,https://i.ytimg.com/vi/bk55RbxiQdI/default.jpg,False,False,False,김장겸 MBC 사장이 결국 해임됐다.\n\nMBC 대주주인 방송문화진흥회는 13일 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34560,pj6YBBrO1sQ,18.14.06,장모님 가게한다고 1억만 달라는 아내 사이다카톡,이슈트래커,24,2018-06-10T23:00:01.000Z,[none],156439,383,58,308,https://i.ytimg.com/vi/pj6YBBrO1sQ/default.jpg,False,False,False,- 남편을 돈줄로만 본 아내- 좋아요와 구독은 언제나 환영입니다.- 카톡시리즈- 모...
34561,_Ne9ER-jr20,18.14.06,여러분~ 렌즈가 이렇게 위험합니다!!!ㅜㅜ _[이슈텔러],이슈텔러 issueTeller,24,2018-06-12T07:00:06.000Z,[none],130948,3121,55,988,https://i.ytimg.com/vi/_Ne9ER-jr20/default.jpg,False,False,False,"안녕하세요~! 이슈텔러 입니다~^^화, 목 오후 4시 / 토요일 오전 9시 재밌고 ..."
34562,xuOQq_fzEjk,18.14.06,2018년 6월 13일 아침 뉴스,News Express,25,2018-06-12T13:17:29.000Z,"한국|""북한""|""미국""|""중국""|""일본""|""러시아""|""한국뉴스""|""뉴스""|""국제뉴스...",62555,319,71,105,https://i.ytimg.com/vi/xuOQq_fzEjk/default.jpg,False,False,False,2018년 6월 13일 아침 뉴스등록되지 않은 구독자가 여기에서 내 새 채널을 지원...
34563,uXvjxeg08eQ,18.14.06,워너원 웃음 참기 영상 워너원 GO X-con.ver,원플,22,2018-06-11T11:57:20.000Z,"워너원|""워너원 고""|""워너원 GO""|""웃음참기""|""워너원 웃음참기""|""워너원 레전...",63306,2369,27,571,https://i.ytimg.com/vi/uXvjxeg08eQ/default.jpg,False,False,False,워너원 웃음 참기 영상 항상 좋아해주셔서 감사합니다8ㅅ8이번에는 얼마전에 있었던 원...
34564,C-bLqIftDY4,18.14.06,[법륜스님의 즉문즉설 제 1398회] 시동생의 아이를 키우게 됐어요,법륜스님의 즉문즉설,29,2018-06-10T20:00:01.000Z,"불교|""즉문즉설""|""법륜스님""|""정토회""|""buddha""|""buddhism""|""po...",63716,500,58,135,https://i.ytimg.com/vi/C-bLqIftDY4/default.jpg,False,False,False,"3월에 시동생이 이혼했습니다 그러면서 제가중2, 7살, 4살 되는 조카들을 데리고 ..."

In [ ]:
KRvideo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34565 entries, 0 to 34564
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                34565 non-null  object
 1   trending_date           34565 non-null  object
 2   title                   34565 non-null  object
 3   channel_title           34565 non-null  object
 4   category_id             34565 non-null  int64
 5   publish_time            34565 non-null  object
 6   tags                    34565 non-null  object
 7   views                   34565 non-null  int64
 8   likes                   34565 non-null  int64
 9   dislikes                34565 non-null  int64
 10  comment_count           34565 non-null  int64
 11  thumbnail_link          34565 non-null  object
 12  comments_disabled       34565 non-null  bool
 13  ratings_disabled        34565 non-null  bool
 14  video_error_or_removed  34565 non-null  bool
 15  description             31403 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 3.5+ MB

In [ ]:
KRvideo.describe()

        category_id         views         likes      dislikes  comment_count
count  34565.000000  3.456500e+04  3.456500e+04  3.456500e+04   3.456500e+04
mean      21.137625  4.249711e+05  1.218712e+04  5.391290e+02   2.025499e+03
std        6.675645  2.430705e+06  1.170565e+05  1.370891e+04   2.150738e+04
min        1.000000  2.050000e+03  0.000000e+00  0.000000e+00   0.000000e+00
25%       22.000000  4.777100e+04  4.120000e+02  2.100000e+01   1.050000e+02
50%       24.000000  1.115280e+05  1.389000e+03  6.500000e+01   3.450000e+02
75%       25.000000  2.788770e+05  3.705000e+03  1.750000e+02   9.290000e+02
max       44.000000  1.138762e+08  5.150839e+06  1.470388e+06   1.142274e+06

In [ ]:
KRvideo.corr()

,category_id,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
category_id,1.000000,-0.082366,-0.097975,-0.016724,-0.065037,0.026885,0.054088,-0.042890
views,-0.082366,1.000000,0.860043,0.581443,0.807600,-0.003380,-0.019286,-0.002113
likes,-0.097975,0.860043,1.000000,0.428036,0.922731,-0.010735,-0.021391,-0.000232
dislikes,-0.016724,0.581443,0.428036,1.000000,0.555549,-0.002056,-0.008080,-0.000589
comment_count,-0.065037,0.807600,0.922731,0.555549,1.000000,-0.011537,-0.014296,-0.000879
comments_disabled,0.026885,-0.003380,-0.010735,-0.002056,-0.011537,1.000000,0.220466,-0.004221
ratings_disabled,0.054088,-0.019286,-0.021391,-0.008080,-0.014296,0.220466,1.000000,-0.007080
video_error_or_removed,-0.042890,-0.002113,-0.000232,-0.000589,-0.000879,-0.004221,-0.007080,1.000000